Content-Type: multipart/mixed; boundary="------------753CbqeS9kQR9hAoiOiqMEvM"
Message-ID: <2308c50f-ddd6-4fc1-a8b5-6b3ec2fd47b1@fit.hcmus.edu.vn>
Date: Wed, 22 Nov 2023 23:32:16 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: hahuy@fit.hcmus.edu.vn
From: Anh Huy <hahuy@fit.hcmus.edu.vn>
Subject: Testing email 01 with file

This is a multi-part message in MIME format.
--------------753CbqeS9kQR9hAoiOiqMEvM
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

Hi Huy,

This is a test.

Thanks.


--------------753CbqeS9kQR9hAoiOiqMEvM
Content-Type: text/plain; charset=UTF-8; name="SATest.cpp"
Content-Disposition: attachment; filename="SATest.cpp"
Content-Transfer-Encoding: base64

I2luY2x1ZGUgIlNBVGVzdC5oIg0KDQp0ZW1wbGF0ZSA8Y2xhc3MgVD4NCm9zdHJlYW0mIG9w
ZXJhdG9yPDwob3N0cmVhbSYgb3MsIGNvbnN0IHZlY3RvcjxUPiYgdikNCnsNCglvcyA8PCAi
WyAiOw0KCWZvciAoYXV0byAgaSA9IDA7IGkgPCB2LnNpemUoKTsgaSsrKQ0KCXsNCgkJb3M8
PHZbaV08PCIgIjsNCgl9DQoJb3MgPDwgIiBdIiA8PCBlbmRsOw0KCXJldHVybiBvczsNCn0N
Cg0KdGVtcGxhdGUgPGNsYXNzIFQ+DQppc3RyZWFtJiBvcGVyYXRvcj4+KGlzdHJlYW0mIGlz
LCAgdmVjdG9yPFQ+JiB2KQ0Kew0KCWludCBuOw0KCWlzID4+IG47DQoJdi5yZXNpemUobik7
DQoJZm9yIChhdXRvIGkgPSAwOyBpIDwgdi5zaXplKCk7IGkrKykNCgl7DQoJCWlzID4+IHZb
aV07DQoJfQ0KCXJldHVybiBpczsNCn0NCg0KDQoNCnRlbXBsYXRlPGNsYXNzIFQ+DQpTQVRl
c3Q8VD46OlNBVGVzdChTb3J0QXJyYXk8VD4qIHBBbGcpDQp7DQoJbUFsZyA9IHBBbGc7DQp9
DQoNCnRlbXBsYXRlIDxjbGFzcyBUPg0Kdm9pZCBTQVRlc3Q8VD46OklucHV0KGlzdHJlYW0m
IGlzKQ0Kew0KCWlzID4+IERhdGE7DQp9DQoNCnRlbXBsYXRlIDxjbGFzcyBUPg0KYm9vbCBT
QVRlc3Q8VD46OkNoZWNrKCkNCnsNCglyZXR1cm4gRGF0YS5zaXplKCkgPiAwOw0KfQ0KDQp0
ZW1wbGF0ZSA8Y2xhc3MgVD4NCnZvaWQgU0FUZXN0PFQ+OjpPdXRwdXQob3N0cmVhbSYgb3Mp
DQp7DQoJb3MgPDwgIlJlc3VsdCBhZnRlciBzb3J0aW5nIDogIjsNCglvcyA8PCBEYXRhOw0K
fQ0KDQp0ZW1wbGF0ZSA8Y2xhc3MgVD4NCnZvaWQgU0FUZXN0PFQ+OjpzdGFydE1lc3NhZ2Uo
b3N0cmVhbSYgb3MpDQp7DQoJb3MgPDwgIkVudGVyIG4sIHRoZW4gYVswXSwgLi4uICwgIGFb
bi0xXTogICI7DQp9DQoNCnRlbXBsYXRlIDxjbGFzcyBUPg0Kdm9pZCBTQVRlc3Q8VD46OnBy
b2Nlc3MoKSB7DQoJaWYgKG1BbGcgIT0gTlVMTCkgbUFsZy0+UHJvY2VzcyhEYXRhKTsNCn0N
Cg==

--------------753CbqeS9kQR9hAoiOiqMEvM--
