Content-Type: multipart/mixed; boundary="===============1160153906176990501=="
MIME-Version: 1.0
date: 08:51:22 08/12/2023
from: codingAkerman@fit.hcmus.edu.vn
to: codingAkerman@fit.hcmus.edu.vn
cc: 
bcc: 
subject: d

--===============1160153906176990501==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

d
--===============1160153906176990501==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename= txtattach2.txt

QmFieSwgSSdtIGRhbmNpbmcgaW4gdGhlIGRhcmsNCldpdGggeW91IGJldHdlZW4gbXkgYXJtcw0K
QmFyZWZvb3Qgb24gdGhlIGdyYXNzDQpMaXN0ZW5pbmcgdG8gb3VyIGZhdm91cml0ZSBzb25nDQpX
aGVuIHlvdSBzYWlkIHlvdSBsb29rZWQgYSBtZXNzDQpJIHdoaXNwZXJlZCB1bmRlcm5lYXRoIG15
IGJyZWF0aA0KQnV0IHlvdSBoZWFyZCBpdA0KRGFybGluZywgeW91IGxvb2sgcGVyZmVjdCB0b25p
Z2h0

--===============1160153906176990501==--
