Content-Type: multipart/mixed; boundary="===============2505030386088202793=="
MIME-Version: 1.0
Date: 09:22:47 07/12/2023
From: codingAkerman@fit.hcmus.edu.vn
To: codingAkerman@fit.hcmus.edu.vn
Cc: 
Bcc: 
Subject: test new mail 1

--===============2505030386088202793==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

2 txt file
--===============2505030386088202793==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename= txtattach.txt

VHLGsOG7nW5nIMSQSCBLSFROLCDEkEhRRy1IQ00gbMOgIHRydW5nIHTDom0gxJHDoG8gdOG6oW8g
xJHhuqFpIGjhu41jLCBzYXUgxJHhuqFpIGjhu41jLCBjdW5nIGPhuqVwIG5ndeG7k24gbmjDom4g
bOG7sWMsIMSR4buZaSBuZ8WpIGNodXnDqm4gZ2lhIHRyw6xuaCDEkeG7mSBjYW8gdHJvbmcgY8Oh
YyBsxKluaCB24buxYyBraG9hIGjhu41jIGPGoSBi4bqjbiwga2hvYSBo4buNYyBsacOqbiBuZ8Og
bmgsIGtob2EgaOG7jWMgY8O0bmcgbmdo4buHIG3FqWkgbmjhu41uLCBjw7MgbsSDbmcgbOG7sWMg
c8OhbmcgdOG6oW8sIGzDoG0gdmnhu4djIHRyb25nIG3DtGkgdHLGsOG7nW5nIGPhuqFuaCB0cmFu
aCBxdeG7kWMgdOG6vzsgbMOgIG7GoWkgdGjhu7FjIGhp4buHbiBuaOG7r25nIG5naGnDqm4gY+G7
qXUga2hvYSBo4buNYyDEkeG7iW5oIGNhbyB04bqhbyByYSBjw6FjIHPhuqNuIHBo4bqpbSB0aW5o
IGhvYSDEkcOhcCDhu6luZyBuaHUgY+G6p3UgcGjDoXQgdHJp4buDbiBLSENOIHbDoCB5w6p1IGPh
uqd1IHBow6F0IHRyaeG7g24ga2luaCB04bq/IC0geMOjIGjhu5lpIG5nw6B5IGPDoG5nIGNhbyBj
4bunYSDEkeG6pXQgbsaw4bubYywgcGjDuSBo4bujcCB24bubaSB4dSB0aOG6vyBwaMOhdCB0cmnh
u4NuIHRo4bq/IGdp4bubaS4NCsSQxrDhu6NjIGdp4bqjbmcgZOG6oXkgYuG7n2kgxJHhu5lpIG5n
xakgR2nDoW8gc8awLCBQaMOzIGdpw6FvIHPGsCB2w6AgR2nhuqNuZyB2acOqbiBow6BuZyDEkeG6
p3UgY8OzIHTDom0gaHV54bq/dCwgdOG6rW4gdMOibSB2w6AgZ2nhu49pIGNodXnDqm4gbcO0bg0K
VGnhur9wIGPhuq1uIHbhu5tpIGPDoWMgY2jGsMahbmcgdHLDrG5oIMSRw6BvIHThuqFvIGPhuq1w
IG5o4bqtdCwgaGnhu4duIMSR4bqhaSB2w6AgxJHhuqF0IGNodeG6qW4gcXXhu5FjIHThur8NCsSQ
xrDhu6NjIHBow6F0IHRyaeG7g24gdG/DoG4gZGnhu4duIGLhuqNuIHRow6JuIHThu6sgY8OhYyB0
cuG6o2kgbmdoaeG7h20gaOG7jWMgdGh14bqtdCwgbmdoacOqbiBj4bupdSBraG9hIGjhu41jLCB0
aOG7sWMgaMOgbmgsIHRo4buxYyB04bq/ICB04bqhaSBkb2FuaCBuZ2hp4buHcA==

--===============2505030386088202793==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename= txtattach2.txt

QmFieSwgSSdtIGRhbmNpbmcgaW4gdGhlIGRhcmsNCldpdGggeW91IGJldHdlZW4gbXkgYXJtcw0K
QmFyZWZvb3Qgb24gdGhlIGdyYXNzDQpMaXN0ZW5pbmcgdG8gb3VyIGZhdm91cml0ZSBzb25nDQpX
aGVuIHlvdSBzYWlkIHlvdSBsb29rZWQgYSBtZXNzDQpJIHdoaXNwZXJlZCB1bmRlcm5lYXRoIG15
IGJyZWF0aA0KQnV0IHlvdSBoZWFyZCBpdA0KRGFybGluZywgeW91IGxvb2sgcGVyZmVjdCB0b25p
Z2h0

--===============2505030386088202793==--
