Content-Type: multipart/mixed; boundary="------------qmlTLEjg9iKDZO66fOIysbMo"
Message-ID: <143b60e6-68a6-4582-a546-13399a7b5452@fitus.edu.vn>
Date: Sun, 26 Nov 2023 00:00:37 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: hahuy@fitus.edu.vn
From: Anh Huy <hahuy@fitus.edu.vn>
Subject: Test mail

This is a multi-part message in MIME format.
--------------qmlTLEjg9iKDZO66fOIysbMo
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

This is a test for mail client project - Computer network 22CLC01

--------------qmlTLEjg9iKDZO66fOIysbMo
Content-Type: text/plain; charset=UTF-8; name="week06.cpp"
Content-Disposition: attachment; filename="week06.cpp"
Content-Transfer-Encoding: base64

77u/I2luY2x1ZGUgPGlvc3RyZWFtPg0KDQojaW5jbHVkZSAiU0FUZXN0LmNwcCINCiNpbmNs
dWRlICJQcm9ncmFtRnJhbWUuY3BwIg0KI2luY2x1ZGUgIkluc2VydGlvblMuY3BwIg0KI2lu
Y2x1ZGUgIkludGVyY2hhbmdlUy5jcHAiDQojaW5jbHVkZSAiU2VsZWN0aW9uUy5jcHAiDQoN
CmludCBtYWluKCkNCnsNCiAgICBjb3V0PDwiLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1TZWxl
Y3Rpb24gU29ydCB3aXRoIElOVEVSR0VSLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0iPDxlbmRs
Ow0KICAgIGF1dG8gc29ydFRlc3QxID1TQVRlc3Q8aW50PiggbmV3IFNlbGVjdGlvblM8aW50
PigpKTsNCiAgICBzb3J0VGVzdDEucnVuKGNpbiwgY291dCk7DQoNCiAgICBjb3V0IDw8ICIt
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLUluc2VydGlvbiBTb3J0IHdpdGggRkxPQVQtLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLSIgPDwgZW5kbDsNCiAgICBhdXRvIHNvcnRUZXN0MiA9IFNBVGVz
dDxmbG9hdD4gKG5ldyBJbnNlcnRpb25TPGZsb2F0PigpKTsNCiAgICBzb3J0VGVzdDIucnVu
KGNpbiwgY291dCk7DQoNCiAgICBjb3V0IDw8ICItLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUlu
c2VydGlvbiBTb3J0IHdpdGggRE9VQkxFLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0iIDw8IGVu
ZGw7DQogICAgYXV0byBzb3J0VGVzdDMgPSBTQVRlc3Q8ZG91YmxlPihuZXcgSW5zZXJ0aW9u
Uzxkb3VibGU+KCkpOw0KICAgIHNvcnRUZXN0My5ydW4oY2luLCBjb3V0KTsNCg0KICAgIGNv
dXQgPDwgIi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tSW50ZXJjaGFuZ2UgU29ydCB3aXRoIFNU
UklORy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIiA8PCBlbmRsOw0KICAgIGF1dG8gc29ydFRl
c3Q0ID0gU0FUZXN0PHN0cmluZz4obmV3IEluc2VydGlvblM8c3RyaW5nPigpKTsNCiAgICBz
b3J0VGVzdDQucnVuKGNpbiwgY291dCk7DQoNCiAgICByZXR1cm4gMDsNCn0NCg0K

--------------qmlTLEjg9iKDZO66fOIysbMo--
