Content-Type: multipart/mixed; boundary="===============2944662680074418554=="
MIME-Version: 1.0
date: 15:09:30 14/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: mail1@gmail.com
subject: this is new mail from hahuy ASAP

--===============2944662680074418554==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

EHLLO
--===============2944662680074418554==--
