Content-Type: multipart/mixed; boundary="===============0124912687869456836=="
MIME-Version: 1.0
date: 17:41:33 11/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: mail1@gmail.com
cc: 
bcc: 
subject: check spam, virus

--===============0124912687869456836==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

virus , hack
--===============0124912687869456836==--
