Content-Type: multipart/mixed; boundary="===============1561384974207762612=="
MIME-Version: 1.0
date: 17:24:00 11/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: mail1@gmail.com
cc: 
bcc: 
subject: ASAP 123546

--===============1561384974207762612==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

test important
--===============1561384974207762612==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename= txtattach2.txt

QmFieSwgSSdtIGRhbmNpbmcgaW4gdGhlIGRhcmsNCldpdGggeW91IGJldHdlZW4gbXkgYXJtcw0K
QmFyZWZvb3Qgb24gdGhlIGdyYXNzDQpMaXN0ZW5pbmcgdG8gb3VyIGZhdm91cml0ZSBzb25nDQpX
aGVuIHlvdSBzYWlkIHlvdSBsb29rZWQgYSBtZXNzDQpJIHdoaXNwZXJlZCB1bmRlcm5lYXRoIG15
IGJyZWF0aA0KQnV0IHlvdSBoZWFyZCBpdA0KRGFybGluZywgeW91IGxvb2sgcGVyZmVjdCB0b25p
Z2h0

--===============1561384974207762612==--
