Content-Type: multipart/mixed; boundary="===============0522657994645665886=="
MIME-Version: 1.0
date: 21:55:22 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: mail1@gmail.com, mail2@gmail.com
bcc: 
subject: test cc 2ppl 02

--===============0522657994645665886==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

02
--===============0522657994645665886==--
