Content-Type: multipart/mixed; boundary="===============2357828902257325879=="
MIME-Version: 1.0
date: 17:35:40 13/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: mail1@gmail.com
cc: 
bcc: hahuy@gmail.com
subject: tesst bcc

--===============2357828902257325879==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

123
--===============2357828902257325879==--
