Content-Type: multipart/mixed; boundary="===============1630953305525845162=="
MIME-Version: 1.0
date: 00:08:12 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: test mail

--===============1630953305525845162==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

no content
--===============1630953305525845162==--
