Content-Type: multipart/mixed; boundary="===============4929467464477337450=="
MIME-Version: 1.0
date: 14:21:26 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: no title

--===============4929467464477337450==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

no content
--===============4929467464477337450==--
