Content-Type: multipart/mixed; boundary="===============2821443854349621200=="
MIME-Version: 1.0
date: 17:37:36 13/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: mail1@gmail.com
cc: 
bcc: hahuy@fitus.edu.vn
subject: checkk bcc

--===============2821443854349621200==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

bcc
--===============2821443854349621200==--
