Content-Type: multipart/mixed; boundary="===============8351450871902251796=="
MIME-Version: 1.0
date: 20:30:19 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: hack, virus, hello

--===============8351450871902251796==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

132
--===============8351450871902251796==--
