Content-Type: multipart/mixed; boundary="===============9188156291382839156=="
MIME-Version: 1.0
date: 14:39:37 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: check result

--===============9188156291382839156==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

no content
--===============9188156291382839156==--
