Content-Type: multipart/mixed; boundary="===============4066587491896808903=="
MIME-Version: 1.0
date: 10:19:18 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: test auto fetch

--===============4066587491896808903==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

no content
--===============4066587491896808903==--
