Content-Type: multipart/mixed; boundary="===============2012242757584902356=="
MIME-Version: 1.0
date: 00:52:56 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: test send mail

--===============2012242757584902356==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

test
--===============2012242757584902356==--
