Content-Type: multipart/mixed; boundary="===============7563503652536993376=="
MIME-Version: 1.0
Date: 15:45:33 11/12/2023
From: codingAkerman@fit.hcmus.edu.vn
To: hahuy@fitus.edu.vn
Cc: 
Bcc: 
Subject: test 

--===============7563503652536993376==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

test with attachment
--===============7563503652536993376==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename= 7-12.txt

bsO6dCB0aG/DoXQgbMO6YyBzb+G6oW4gbWFpbCBi4buLIGzhu5dpDQprbyBzb+G6oW4gbmhp4buB
dSBtYWlsIGPDuW5nIGzDumMgZGMNCmNo4buJIHQgbG9hZCBqc29uIGzDqm4gbWFpbGJveCBj4bun
YSBhcHA=

--===============7563503652536993376==--
