Content-Type: multipart/mixed; boundary="===============5726461305839031948=="
MIME-Version: 1.0
Date: 15:44:23 11/12/2023
From: codingAkerman@fit.hcmus.edu.vn
To: hahuy@fitus.edu.vn
Cc: 
Bcc: 
Subject: test test

--===============5726461305839031948==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

test without attachment
--===============5726461305839031948==--
