Content-Type: multipart/mixed; boundary="===============4352672521033016997=="
MIME-Version: 1.0
date: 00:51:01 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: test send mail

--===============4352672521033016997==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

this is a test
--===============4352672521033016997==--
