Content-Type: multipart/mixed; boundary="===============1060930721625233042=="
MIME-Version: 1.0
date: 11:45:50 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: fix fetch mail

--===============1060930721625233042==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

check bugs
--===============1060930721625233042==--
