Content-Type: multipart/mixed; boundary="===============8087827937209786295=="
MIME-Version: 1.0
Date: 00:13:33 10/12/2023
From: codingAkerman@fit.hcmus.edu.vn
To: hahuy@fitus.edu.vn
Cc: 
Bcc: 
Subject: send attachment

--===============8087827937209786295==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

dfa
--===============8087827937209786295==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename= C:\Users\ADMIN\Downloads\7-12.txt

bsO6dCB0aG/DoXQgbMO6YyBzb+G6oW4gbWFpbCBi4buLIGzhu5dpDQprbyBzb+G6oW4gbmhp4buB
dSBtYWlsIGPDuW5nIGzDumMgZGMNCmNo4buJIHQgbG9hZCBqc29uIGzDqm4gbWFpbGJveCBj4bun
YSBhcHA=

--===============8087827937209786295==--
