Content-Type: multipart/mixed; boundary="===============5007502039835581156=="
MIME-Version: 1.0
date: 14:29:21 12/12/2023
sender: codingAkerman@fit.hcmus.edu.vn
to: hahuy@fitus.edu.vn
cc: 
bcc: 
subject: mail2

--===============5007502039835581156==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

content this is a content content
--===============5007502039835581156==--
